<?php

/**
 * Bridge design tokens — storage, resolution and sanitisation.
 *
 * The token record is the single source of truth for the site's design
 * system. It is resolved from three layers, lowest priority first:
 *
 *   1. bridge_token_defaults()   Hardcoded, always complete. The theme still
 *                                works if every other layer is missing.
 *   2. design/tokens.json        Per-client seed, committed to the repo. Where
 *                                a Figma export lands.
 *   3. bridge_theme_options      What an operator saved in the admin.
 *
 * The resolved array is then sanitised into a guaranteed-complete, valid
 * structure — every consumer can read it without defensive checks.
 *
 * Nothing here knows about theme.json. Compilation lives in inc/theme-json.php.
 *
 * @package Bridge
 */

declare(strict_types=1);

if (! defined('ABSPATH')) {
	exit;
}

/**
 * Where operator-saved values live. Autoloaded — it is read on every request.
 */
define('BRIDGE_TOKENS_OPTION', 'bridge_theme_options');

/**
 * Fingerprint of the current token set, refreshed whenever tokens change.
 *
 * Not a cache-buster for dist/main.css — that file compiles no token values,
 * it only references the CSS custom properties WordPress prints inline. This
 * is a change signal for token-derived artefacts that arrive in later phases
 * (font preloads, the icon sprite) and for external cache purging.
 */
define('BRIDGE_TOKENS_VERSION_OPTION', 'bridge_tokens_version');

/**
 * The palette slugs the theme guarantees, in editor display order.
 *
 * Fixed by the theme, never by the client. Slugs are written into post content
 * as class names (`has-primary-color`, `has-surface-background-color`), so
 * renaming or removing one silently restyles every page that used it. Only the
 * hex and the display name are configurable.
 *
 * @return array<string, string> Slug => default display name.
 */
function bridge_palette_slugs(): array
{
	return array(
		'primary'    => 'Primary',
		'secondary'  => 'Secondary',
		'accent'     => 'Accent',
		'background' => 'Background',
		'surface'    => 'Surface',
		'text'       => 'Text',
	);
}

/**
 * The hex a palette slug currently resolves to.
 *
 * Read from the token record rather than from the compiled global settings:
 * the tokens are the source, the palette in theme.json is a copy of them, and
 * a caller that wants to reason about a colour — pick a readable foreground
 * against it, most often — should ask the thing that decides rather than the
 * thing that was told.
 *
 * @param string $slug Palette slug.
 * @return string A `#rrggbb` value, or '' when the slug is not a theme colour.
 */
function bridge_palette_hex(string $slug): string
{
	$palette = bridge_get_tokens()['brand']['palette'];

	return isset($palette[$slug]['color']) ? (string) $palette[$slug]['color'] : '';
}

/**
 * Spacing preset slugs generated by the theme's 7-step spacing scale.
 *
 * The step count is deliberately not configurable: WordPress derives these
 * slugs from it, and theme.json plus the SCSS layer reference them by name.
 * Changing the count would renumber every existing spacing choice.
 *
 * Cast back to strings: PHP turns the numeric keys of bridge_spacing_steps()
 * into integers, and the slugs are compared strictly against submitted values,
 * which arrive from REST as strings.
 *
 * @return string[]
 */
function bridge_spacing_slugs(): array
{
	return array_map('strval', array_keys(bridge_spacing_steps()));
}

/**
 * The spacing scale, slug to the name an operator sees.
 *
 * The slugs are numbers because WordPress derives them from the step count and
 * writes them into post content; the names are t-shirt sizes because "L" is a
 * thing a person can choose between and `spacing--70` is not. One scale, named
 * once, offered by every control that spends spacing — block gap, page side
 * padding, section padding — so a site can be tightened or opened up by moving
 * several settings through the same vocabulary.
 *
 * @return array<string, string> Slug => display name, smallest first.
 */
function bridge_spacing_steps(): array
{
	return array(
		'20' => 'XS',
		'30' => 'S',
		'40' => 'M',
		'50' => 'L',
		'60' => 'XL',
		'70' => '2XL',
		'80' => '3XL',
	);
}

/**
 * The valid range or option set for every numeric and enumerated token.
 *
 * One source of truth, consumed by both the sanitiser and the REST route that
 * feeds the options page. Split across two definitions, a slider would sooner
 * or later offer a value the server silently clamps — which reads to the
 * operator as the page ignoring them.
 *
 * @return array<string, array<string, array<string, mixed>>>
 */
function bridge_token_constraints(): array
{
	return array(
		'typography' => array(
			// Below 0.75rem body copy stops being readable; above 1.5rem the
			// fluid clamps at the top of the scale start to overlap.
			'baseSize'          => array('min' => 0.75, 'max' => 1.5, 'step' => 0.0625, 'unit' => 'rem'),
			// Below ~1.05 the scale collapses into one size; above 2.0 an h1
			// dwarfs a phone viewport even after fluid compression.
			'scaleRatio'        => array('min' => 1.05, 'max' => 2.0, 'step' => 0.005),
			'bodyLineHeight'    => array('min' => 1.1, 'max' => 2.2, 'step' => 0.05),
			'headingLineHeight' => array('min' => 0.9, 'max' => 1.8, 'step' => 0.05),
			'headingWeight'     => array('options' => array('300', '400', '500', '600', '700', '800', '900')),
			'headingCase'       => array('options' => array('none', 'uppercase')),
		),
		'icons'      => array(
			'weight' => array('options' => array('regular', 'bold')),
		),
		'header'     => array(
			// Every layout stacks or rows the same two elements; none puts the
			// menu in a fixed centre column, which would cap how many items it
			// can hold as a client's services grow.
			'layout'       => array('options' => array('left', 'centre', 'two-row')),
			'background'   => array('options' => array('solid', 'transparent')),
			'contrast'     => array('options' => array('auto', 'light', 'dark')),
			'logoHeight'   => array('min' => 16, 'max' => 120, 'step' => 2, 'unit' => 'px'),
			// 0 is a header whose logo touches the edges of its ground — flush
			// is a legitimate look, so it is a legitimate value. Above ~80 the
			// bar stops reading as a header and starts reading as a section.
			'paddingBlock' => array('min' => 0, 'max' => 80, 'step' => 2, 'unit' => 'px'),
		),
		'footer'     => array(
			'style' => array('options' => array('simple', 'columns')),
		),
		'layout'     => array(
			'contentSize'      => array('min' => 320, 'max' => 1600, 'step' => 10, 'unit' => 'px'),
			'wideSize'         => array('min' => 480, 'max' => 2400, 'step' => 10, 'unit' => 'px'),
			'spacingBase'      => array('min' => 0.5, 'max' => 4.0, 'step' => 0.25, 'unit' => 'rem'),
			'spacingIncrement' => array('min' => 1.1, 'max' => 2.0, 'step' => 0.05),
			'blockGap'         => array('options' => bridge_spacing_slugs()),
			'rootPadding'      => array('options' => bridge_spacing_slugs()),
			'sectionPadding'   => array('options' => bridge_spacing_slugs()),
		),
	);
}

/**
 * Complete fallback token set.
 *
 * Mirrors the shipped design/tokens.json, but lives in code so the theme can
 * never be left without a valid design system.
 *
 * @return array<string, mixed>
 */
function bridge_token_defaults(): array
{
	$palette = array();
	foreach (bridge_palette_slugs() as $slug => $name) {
		$palette[$slug] = array(
			'color' => '#000000',
			'name'  => $name,
		);
	}

	$palette['primary']['color']    = '#0F172A';
	$palette['secondary']['color']  = '#2563EB';
	$palette['accent']['color']     = '#F59E0B';
	$palette['background']['color'] = '#FFFFFF';
	$palette['surface']['color']    = '#F5F5F4';
	$palette['text']['color']       = '#1F2937';

	return array(
		'brand'      => array(
			'palette' => $palette,
		),
		'typography' => array(
			'fontSet'           => 'system',
			'googleFonts'       => false,
			'googleHeading'     => '',
			'googleBody'        => '',
			'baseSize'          => 1.0,
			'scaleRatio'        => 1.5,
			'headingWeight'     => '600',
			'headingCase'       => 'none',
			'bodyLineHeight'    => 1.6,
			'headingLineHeight' => 1.2,
		),
		'icons'      => array(
			'weight' => 'regular',
		),
		'header'     => array(
			'layout'          => 'left',
			'topBar'          => false,
			// 0 means "let core pick" — a fresh site has no menus yet, and a
			// header that renders nothing until someone visits a settings page
			// is worse than one that guesses.
			'menus'           => array('primary' => 0, 'utility' => 0),
			'background'      => 'solid',
			'backgroundColor' => 'background',
			'contrast'        => 'auto',
			'sticky'          => false,
			'border'          => false,
			// The air above and below the logo at full width, in pixels. Near
			// the 0.67rem the header used before this was a setting, so a site
			// that never opens the control keeps the height it had.
			'paddingBlock'    => 12,
			// Two images of one wordmark: `id` is the dark logo, drawn for a
			// light ground, and `lightId` the light one for a dark ground.
			// Either may be 0 — a site with a single logo uses it everywhere.
			'logo'            => array('id' => 0, 'lightId' => 0, 'height' => 40),
			'cta'             => array('enabled' => false, 'label' => '', 'url' => ''),
		),
		'footer'     => array(
			'style' => 'simple',
		),
		// Deviations from the theme's curated block set, not the set itself.
		// Storing the whole list would freeze it: a block added by a later
		// theme release would arrive switched off, because it could not be in
		// a list written before it existed.
		'blocks'     => array(
			'enabled'  => array(),
			'disabled' => array(),
		),
		'layout'     => array(
			'contentSize'      => 720,
			'wideSize'         => 1200,
			'spacingBase'      => 1.5,
			'spacingIncrement' => 1.5,
			'blockGap'         => '40',
			'rootPadding'      => '40',
			// The air above and below a section. Two steps above the page's
			// side padding: vertical rhythm carries the separation between one
			// section and the next, where the horizontal gutter only has to
			// keep text off the edge of the screen.
			'sectionPadding'   => '70',
		),
		// Not design: what WordPress serves *alongside* the pages. Grouped
		// apart from the visual tokens because nothing here compiles into
		// theme.json — these values are read by inc/wp-clean.php, which only
		// ever removes output.
		'site'       => array(
			'feeds' => false,
		),
	);
}

/**
 * The curated font sets, keyed by slug.
 *
 * @return array<string, array<string, mixed>>
 */
function bridge_font_sets(): array
{
	static $sets = null;

	if (null !== $sets) {
		return $sets;
	}

	$sets = array();
	$path = get_theme_file_path('design/font-sets.json');

	if (file_exists($path)) {
		$data = wp_json_file_decode($path, array('associative' => true));

		if (is_array($data)) {
			foreach ($data as $slug => $set) {
				// Skip the "$comment" key and any malformed entry.
				if (! is_array($set) || empty($set['families']) || ! is_array($set['families'])) {
					continue;
				}

				$sets[(string) $slug] = $set;
			}
		}
	}

	// A set named `system` is the guaranteed fallback for an invalid choice, so
	// synthesise one if the manifest is missing or unreadable.
	if (! isset($sets['system'])) {
		$sets['system'] = array(
			'name'     => 'System',
			'families' => array(
				'sans'  => "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
				'serif' => "Georgia, 'Times New Roman', Times, serif",
				'mono'  => 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
			),
		);
	}

	return $sets;
}

/**
 * The committed per-client seed, or an empty array if none ships.
 *
 * @return array<string, mixed>
 */
function bridge_token_seed(): array
{
	static $seed = null;

	if (null !== $seed) {
		return $seed;
	}

	$seed = array();
	$path = get_theme_file_path('design/tokens.json');

	if (file_exists($path)) {
		$data = wp_json_file_decode($path, array('associative' => true));

		if (is_array($data)) {
			$seed = $data;
		}
	}

	return $seed;
}

/**
 * Recursively merge $overrides into $base, associative keys only.
 *
 * Unlike array_merge_recursive() this replaces scalars rather than collecting
 * them into arrays, which is what layering partial token overrides needs.
 *
 * A list — `blocks.disabled`, `blocks.enabled` — is one value, not a map of
 * positions, so it is replaced whole. Merging it by index would let a list
 * grow but never shrink: dropping a block from `disabled` would leave the
 * lower layer's entry sitting at the same index, and switching a block back on
 * would silently do nothing.
 *
 * @param array<string, mixed> $base      Lower-priority values.
 * @param array<string, mixed> $overrides Higher-priority values.
 * @return array<string, mixed>
 */
function bridge_merge_deep(array $base, array $overrides): array
{
	foreach ($overrides as $key => $value) {
		if (
			is_array($value)
			&& isset($base[$key])
			&& is_array($base[$key])
			&& ! array_is_list($value)
			&& ! array_is_list($base[$key])
		) {
			$base[$key] = bridge_merge_deep($base[$key], $value);
			continue;
		}

		$base[$key] = $value;
	}

	return $base;
}

/**
 * Runtime memo for the resolved token set.
 *
 * Kept in its own accessor so bridge_flush_tokens() can clear it — the
 * resolver may read tokens again later in the same request that saved them.
 *
 * @param array<string, mixed>|null $value Array to store, or null to read.
 * @param bool                      $clear Drop the stored value.
 * @return array<string, mixed>|null
 */
function bridge_tokens_memo(?array $value = null, bool $clear = false): ?array
{
	static $memo = null;

	if ($clear) {
		$memo = null;

		return null;
	}

	if (null !== $value) {
		$memo = $value;
	}

	return $memo;
}

/**
 * The resolved, sanitised, guaranteed-complete token set.
 *
 * @return array<string, mixed>
 */
function bridge_get_tokens(): array
{
	$memo = bridge_tokens_memo();

	if (null !== $memo) {
		return $memo;
	}

	$stored = get_option(BRIDGE_TOKENS_OPTION, array());
	$raw    = bridge_merge_deep(bridge_token_seed(), is_array($stored) ? $stored : array());

	$tokens = bridge_sanitize_tokens($raw);
	bridge_tokens_memo($tokens);

	return $tokens;
}

/**
 * Clamp a value into a numeric range, falling back when it isn't a number.
 *
 * @param mixed $value    Candidate.
 * @param float $min      Lower bound, inclusive.
 * @param float $max      Upper bound, inclusive.
 * @param float $fallback Used when $value is not numeric.
 */
function bridge_clamp_float($value, float $min, float $max, float $fallback): float
{
	if (! is_numeric($value)) {
		return $fallback;
	}

	return min($max, max($min, (float) $value));
}

/**
 * Clamp a token against its declared constraint.
 *
 * @param string $group    Token group: `typography` or `layout`.
 * @param string $key      Token key.
 * @param mixed  $value    Candidate.
 * @param float  $fallback Used when $value is not numeric.
 */
function bridge_clamp_token(string $group, string $key, $value, float $fallback): float
{
	$constraint = bridge_token_constraints()[$group][$key];

	return bridge_clamp_float($value, (float) $constraint['min'], (float) $constraint['max'], $fallback);
}

/**
 * Accept a token only if it is one of its declared options.
 *
 * @param string $group    Token group: `typography` or `layout`.
 * @param string $key      Token key.
 * @param mixed  $value    Candidate.
 * @param string $fallback Used when $value is not a valid option.
 */
function bridge_pick_token(string $group, string $key, $value, string $fallback): string
{
	$options = bridge_token_constraints()[$group][$key]['options'];

	return in_array((string) $value, $options, true) ? (string) $value : $fallback;
}

/**
 * Reduce arbitrary input to a complete, valid token set.
 *
 * Total by design: anything missing, malformed or out of range is replaced
 * with the default rather than rejected, so a half-filled REST payload or a
 * hand-edited option can never produce a broken design system. This is the
 * only place token input is trusted — validate on write, not on read.
 *
 * @param array<string, mixed> $raw Candidate tokens, possibly partial.
 * @return array<string, mixed>
 */
function bridge_sanitize_tokens(array $raw): array
{
	$defaults = bridge_token_defaults();

	// ---- Brand palette ----------------------------------------------------
	$palette     = array();
	$raw_palette = isset($raw['brand']['palette']) && is_array($raw['brand']['palette'])
		? $raw['brand']['palette']
		: array();

	foreach (bridge_palette_slugs() as $slug => $default_name) {
		$entry = isset($raw_palette[$slug]) && is_array($raw_palette[$slug]) ? $raw_palette[$slug] : array();

		// sanitize_hex_color() requires a leading # and 3 or 6 hex digits, and
		// returns null for anything else — exactly the guarantee downstream
		// contrast maths and CSS output need.
		$color = isset($entry['color']) ? sanitize_hex_color((string) $entry['color']) : null;

		$name = isset($entry['name']) ? sanitize_text_field((string) $entry['name']) : '';

		$palette[$slug] = array(
			'color' => $color ?? $defaults['brand']['palette'][$slug]['color'],
			'name'  => '' !== $name ? $name : $default_name,
		);
	}

	// ---- Typography -------------------------------------------------------
	$raw_type = isset($raw['typography']) && is_array($raw['typography']) ? $raw['typography'] : array();
	$dt       = $defaults['typography'];

	$font_set = isset($raw_type['fontSet']) ? sanitize_key((string) $raw_type['fontSet']) : '';
	if (! isset(bridge_font_sets()[$font_set])) {
		$font_set = $dt['fontSet'];
	}

	// Google families are validated against the curated catalogue, never
	// accepted as free text: the name is interpolated into an outbound URL and
	// becomes a directory name on disk.
	$google_on = ! empty($raw_type['googleFonts']);

	// Validated per role, not against the whole catalogue: the heading and
	// body lists differ, and a face chosen for the wrong job is a mistake
	// worth catching here rather than shipping to a client's homepage.
	$google_family = static function ($value, string $role) use ($google_on): string {
		$family = is_string($value) ? trim($value) : '';

		if (! $google_on || '' === $family || ! function_exists('bridge_google_families_for')) {
			return '';
		}

		return in_array($family, bridge_google_families_for($role), true) ? $family : '';
	};

	$typography = array(
		'fontSet'           => $font_set,
		'googleFonts'       => $google_on,
		'googleHeading'     => $google_family($raw_type['googleHeading'] ?? '', 'heading'),
		'googleBody'        => $google_family($raw_type['googleBody'] ?? '', 'body'),
		'baseSize'          => bridge_clamp_token('typography', 'baseSize', $raw_type['baseSize'] ?? null, (float) $dt['baseSize']),
		'scaleRatio'        => bridge_clamp_token('typography', 'scaleRatio', $raw_type['scaleRatio'] ?? null, (float) $dt['scaleRatio']),
		'headingWeight'     => bridge_pick_token('typography', 'headingWeight', $raw_type['headingWeight'] ?? '', $dt['headingWeight']),
		'headingCase'       => bridge_pick_token('typography', 'headingCase', $raw_type['headingCase'] ?? '', $dt['headingCase']),
		'bodyLineHeight'    => bridge_clamp_token('typography', 'bodyLineHeight', $raw_type['bodyLineHeight'] ?? null, (float) $dt['bodyLineHeight']),
		'headingLineHeight' => bridge_clamp_token('typography', 'headingLineHeight', $raw_type['headingLineHeight'] ?? null, (float) $dt['headingLineHeight']),
	);

	// ---- Layout -----------------------------------------------------------
	$raw_layout = isset($raw['layout']) && is_array($raw['layout']) ? $raw['layout'] : array();
	$dl         = $defaults['layout'];

	$content_size = (int) round(bridge_clamp_token('layout', 'contentSize', $raw_layout['contentSize'] ?? null, (float) $dl['contentSize']));
	$wide_size    = (int) round(bridge_clamp_token('layout', 'wideSize', $raw_layout['wideSize'] ?? null, (float) $dl['wideSize']));

	// A wide width narrower than the content width makes `alignwide` visibly
	// smaller than the default column — always a mistake, never a choice.
	if ($wide_size < $content_size) {
		$wide_size = $content_size;
	}

	$layout = array(
		'contentSize'      => $content_size,
		'wideSize'         => $wide_size,
		'spacingBase'      => bridge_clamp_token('layout', 'spacingBase', $raw_layout['spacingBase'] ?? null, (float) $dl['spacingBase']),
		'spacingIncrement' => bridge_clamp_token('layout', 'spacingIncrement', $raw_layout['spacingIncrement'] ?? null, (float) $dl['spacingIncrement']),
		'blockGap'         => bridge_pick_token('layout', 'blockGap', $raw_layout['blockGap'] ?? '', $dl['blockGap']),
		'rootPadding'      => bridge_pick_token('layout', 'rootPadding', $raw_layout['rootPadding'] ?? '', $dl['rootPadding']),
		'sectionPadding'   => bridge_pick_token('layout', 'sectionPadding', $raw_layout['sectionPadding'] ?? '', $dl['sectionPadding']),
	);

	// ---- Icons ------------------------------------------------------------
	$raw_icons = isset($raw['icons']) && is_array($raw['icons']) ? $raw['icons'] : array();

	$icons = array(
		'weight' => bridge_pick_token('icons', 'weight', $raw_icons['weight'] ?? '', $defaults['icons']['weight']),
	);

	// ---- Structure --------------------------------------------------------
	$raw_header = isset($raw['header']) && is_array($raw['header']) ? $raw['header'] : array();
	$raw_footer = isset($raw['footer']) && is_array($raw['footer']) ? $raw['footer'] : array();

	// The nested groups, read once. Without these the `?? ` fallbacks below
	// silently swallow an undefined variable and every logo and button setting
	// resolves to its default no matter what was saved.
	$raw_logo  = isset($raw_header['logo']) && is_array($raw_header['logo']) ? $raw_header['logo'] : array();
	$raw_cta   = isset($raw_header['cta']) && is_array($raw_header['cta']) ? $raw_header['cta'] : array();
	$raw_menus = isset($raw_header['menus']) && is_array($raw_header['menus']) ? $raw_header['menus'] : array();

	// `ctaBar` was this setting's name before the strip stopped holding the call
	// to action. Either key switches the bar on, so a site saved before the
	// rename keeps its bar. Deliberately an OR rather than "new key wins":
	// the seed ships `topBar` too, so an absent-key test would always find the
	// new key present and never reach the old one. Nothing is stuck on — the
	// options page submits a complete draft, so the first save writes the
	// record without the legacy key and this stops mattering.
	$top_bar = ! empty($raw_header['topBar']) || ! empty($raw_header['ctaBar']);

	// `inverseId` was the light logo's name while it was only ever shown under
	// a transparent header. Read when the new key is absent or empty rather
	// than only when it is absent: the seed ships `lightId`, so the merge hands
	// the sanitiser both keys and a plain `??` would always stop at the new
	// one. Nothing is lost by the looser test — 0 means "no light logo", which
	// is exactly when the old key is worth consulting.
	$light_id = max(0, (int) ($raw_logo['lightId'] ?? 0));

	if ($light_id <= 0) {
		$light_id = max(0, (int) ($raw_logo['inverseId'] ?? 0));
	}

	$cta_label = sanitize_text_field((string) ($raw_cta['label'] ?? ''));
	// esc_url_raw rather than a bare string: this becomes an href, and a
	// javascript: URL in a header would run on every page.
	$cta_url = esc_url_raw((string) ($raw_cta['url'] ?? ''));

	// The button used to be implied by having filled in both fields. Records
	// written under that rule carry no `enabled` key, so infer it from the
	// fields rather than switching an existing site's button off on upgrade.
	$cta_enabled = array_key_exists('enabled', $raw_cta)
		? ! empty($raw_cta['enabled'])
		: ('' !== $cta_label && '' !== $cta_url);

	$header = array(
		'layout'          => bridge_pick_token('header', 'layout', $raw_header['layout'] ?? '', $defaults['header']['layout']),
		'topBar'          => ! empty($top_bar),
		// Structural validation only. Whether the id still points at a live
		// menu is a question for render time — a menu deleted after it was
		// chosen must not silently rewrite the stored setting to 0, or the
		// choice is lost the moment someone opens the options page.
		'menus'           => array(
			'primary' => max(0, (int) ($raw_menus['primary'] ?? 0)),
			'utility' => max(0, (int) ($raw_menus['utility'] ?? 0)),
		),
		'background'      => bridge_pick_token('header', 'background', $raw_header['background'] ?? '', $defaults['header']['background']),
		'backgroundColor' => isset(bridge_palette_slugs()[(string) ($raw_header['backgroundColor'] ?? '')])
			? (string) $raw_header['backgroundColor']
			: $defaults['header']['backgroundColor'],
		'contrast'        => bridge_pick_token('header', 'contrast', $raw_header['contrast'] ?? '', $defaults['header']['contrast']),
		'sticky'          => ! empty($raw_header['sticky']),
		'border'          => ! empty($raw_header['border']),
		'paddingBlock'    => (int) round(bridge_clamp_token('header', 'paddingBlock', $raw_header['paddingBlock'] ?? null, (float) $defaults['header']['paddingBlock'])),
		'logo'            => array(
			'id'      => max(0, (int) ($raw_logo['id'] ?? 0)),
			'lightId' => $light_id,
			'height'  => (int) round(bridge_clamp_token('header', 'logoHeight', $raw_logo['height'] ?? null, (float) $defaults['header']['logo']['height'])),
		),
		'cta'             => array(
			'enabled' => $cta_enabled,
			'label'   => $cta_label,
			'url'     => $cta_url,
		),
	);

	$footer = array(
		'style' => bridge_pick_token('footer', 'style', $raw_footer['style'] ?? '', $defaults['footer']['style']),
	);

	// ---- Site output ------------------------------------------------------
	$raw_site = isset($raw['site']) && is_array($raw['site']) ? $raw['site'] : array();

	// Cast rather than defaulted: a boolean's "missing" and "off" are the same
	// answer, so there is nothing for a fallback to disambiguate.
	$site = array(
		'feeds' => ! empty($raw_site['feeds']),
	);

	// ---- Blocks -----------------------------------------------------------
	$raw_blocks = isset($raw['blocks']) && is_array($raw['blocks']) ? $raw['blocks'] : array();

	// Sorted and de-duplicated so two records describing the same set are
	// byte-identical — the options page compares them to decide whether there
	// is anything to save.
	$block_names = static function ($value): array {
		$names = array();

		foreach ((array) $value as $name) {
			if (! is_string($name)) {
				continue;
			}

			$name = strtolower(trim($name));

			// namespace/name is the only shape a block name takes, and this
			// value ends up in comparisons against the block registry.
			if (preg_match('#^[a-z][a-z0-9-]*/[a-z][a-z0-9-]*$#', $name)) {
				$names[] = $name;
			}
		}

		$names = array_values(array_unique($names));
		sort($names);

		return $names;
	};

	$disabled = $block_names($raw_blocks['disabled'] ?? array());
	$enabled  = $block_names($raw_blocks['enabled'] ?? array());

	// The editor cannot function without a few of these, so switching them off
	// is not a choice the record is allowed to hold.
	$disabled = array_values(array_diff($disabled, bridge_required_blocks()));

	// Off wins: a block in both lists is a contradiction, and the safer
	// reading of a contradiction in a locked-down theme is the narrower one.
	$enabled = array_values(array_diff($enabled, $disabled));

	return array(
		'brand'      => array('palette' => $palette),
		'typography' => $typography,
		'icons'      => $icons,
		'header'     => $header,
		'footer'     => $footer,
		'layout'     => $layout,
		'blocks'     => array(
			'enabled'  => $enabled,
			'disabled' => $disabled,
		),
		'site'       => $site,
	);
}

/**
 * Persist a token set, sanitising first.
 *
 * The full sanitised structure is stored rather than a sparse diff, so the
 * record is self-describing and portable to another site.
 *
 * @param array<string, mixed> $tokens Candidate tokens, possibly partial.
 * @return bool True when the stored value changed.
 */
function bridge_update_tokens(array $tokens): bool
{
	return update_option(BRIDGE_TOKENS_OPTION, bridge_sanitize_tokens($tokens), true);
}

/**
 * Merge a partial token fragment into what is already stored.
 *
 * @param array<string, mixed> $fragment Partial tokens.
 * @return bool True when the stored value changed.
 */
function bridge_patch_tokens(array $fragment): bool
{
	return bridge_update_tokens(bridge_merge_deep(bridge_get_tokens(), $fragment));
}

/**
 * Short fingerprint of the current token set.
 */
function bridge_tokens_fingerprint(): string
{
	return substr(md5((string) wp_json_encode(bridge_get_tokens())), 0, 12);
}

/**
 * The stored token fingerprint, for versioning token-derived assets.
 */
function bridge_tokens_version(): string
{
	$version = get_option(BRIDGE_TOKENS_VERSION_OPTION, '');

	return is_string($version) && '' !== $version ? $version : bridge_tokens_fingerprint();
}

/**
 * Drop every cached copy of the design system after a token change.
 *
 * Three caches matter, and missing any one produces the classic "I saved it
 * but nothing changed" report:
 *
 *   - Our own request-level memo.
 *   - WordPress's resolved theme.json (static properties on the resolver).
 *   - The generated global stylesheet in the object cache, which persists
 *     across requests wherever Redis or Memcached is configured.
 *
 * wp_clean_theme_json_cache() covers the last two.
 */
function bridge_flush_tokens(): void
{
	bridge_tokens_memo(null, true);

	if (function_exists('wp_clean_theme_json_cache')) {
		wp_clean_theme_json_cache();
	}

	$tokens = bridge_get_tokens();

	update_option(BRIDGE_TOKENS_VERSION_OPTION, bridge_tokens_fingerprint(), true);

	/**
	 * Fires after the design tokens change and every cache has been dropped.
	 *
	 * Later phases hang font preloading and icon sprite regeneration here;
	 * hosting-level cache purges belong here too.
	 *
	 * @param array<string, mixed> $tokens The newly resolved token set.
	 */
	do_action('bridge_tokens_changed', $tokens);
}

/**
 * Flush whenever the token option is written, however it was written.
 *
 * Hooking the generic option actions rather than the option-specific ones
 * catches direct update_option() calls from WP-CLI, migrations and future
 * REST handlers alike. All three pass the option name as the first argument.
 *
 * @param string $option Option name that changed.
 */
function bridge_maybe_flush_tokens($option): void
{
	if (BRIDGE_TOKENS_OPTION === $option) {
		bridge_flush_tokens();
	}
}
add_action('added_option', 'bridge_maybe_flush_tokens');
add_action('updated_option', 'bridge_maybe_flush_tokens');
add_action('deleted_option', 'bridge_maybe_flush_tokens');
