<?php

/**
 * Bridge design tokens — storage, resolution and sanitisation.
 *
 * The token record is the single source of truth for the site's design
 * system. It is resolved from three layers, lowest priority first:
 *
 *   1. bridge_token_defaults()   Hardcoded, always complete. The theme still
 *                                works if every other layer is missing.
 *   2. design/tokens.json        Per-client seed, committed to the repo. Where
 *                                a Figma export lands.
 *   3. bridge_theme_options      What an operator saved in the admin.
 *
 * The resolved array is then sanitised into a guaranteed-complete, valid
 * structure — every consumer can read it without defensive checks.
 *
 * Nothing here knows about theme.json. Compilation lives in inc/theme-json.php.
 *
 * @package Bridge
 */

declare(strict_types=1);

if (! defined('ABSPATH')) {
	exit;
}

/**
 * Where operator-saved values live. Autoloaded — it is read on every request.
 */
define('BRIDGE_TOKENS_OPTION', 'bridge_theme_options');

/**
 * Fingerprint of the current token set, refreshed whenever tokens change.
 *
 * Not a cache-buster for dist/main.css — that file compiles no token values,
 * it only references the CSS custom properties WordPress prints inline. This
 * is a change signal for token-derived artefacts that arrive in later phases
 * (font preloads, the icon sprite) and for external cache purging.
 */
define('BRIDGE_TOKENS_VERSION_OPTION', 'bridge_tokens_version');

/**
 * The palette slugs the theme guarantees, in editor display order.
 *
 * Fixed by the theme, never by the client. Slugs are written into post content
 * as class names (`has-primary-color`, `has-surface-background-color`), so
 * renaming or removing one silently restyles every page that used it. Only the
 * hex and the display name are configurable.
 *
 * @return array<string, string> Slug => default display name.
 */
function bridge_palette_slugs(): array
{
	return array(
		'primary'    => 'Primary',
		'secondary'  => 'Secondary',
		'accent'     => 'Accent',
		'background' => 'Background',
		'surface'    => 'Surface',
		'text'       => 'Text',
	);
}

/**
 * The hex a palette slug currently resolves to.
 *
 * Read from the token record rather than from the compiled global settings:
 * the tokens are the source, the palette in theme.json is a copy of them, and
 * a caller that wants to reason about a colour — pick a readable foreground
 * against it, most often — should ask the thing that decides rather than the
 * thing that was told.
 *
 * @param string $slug Palette slug.
 * @return string A `#rrggbb` value, or '' when the slug is not a theme colour.
 */
function bridge_palette_hex(string $slug): string
{
	$palette = bridge_get_tokens()['brand']['palette'];

	return isset($palette[$slug]['color']) ? (string) $palette[$slug]['color'] : '';
}

/**
 * Spacing preset slugs generated by the theme's 7-step spacing scale.
 *
 * The step count is deliberately not configurable: WordPress derives these
 * slugs from it, and theme.json plus the SCSS layer reference them by name.
 * Changing the count would renumber every existing spacing choice.
 *
 * Cast back to strings: PHP turns the numeric keys of bridge_spacing_steps()
 * into integers, and the slugs are compared strictly against submitted values,
 * which arrive from REST as strings.
 *
 * @return string[]
 */
function bridge_spacing_slugs(): array
{
	return array_map('strval', array_keys(bridge_spacing_steps()));
}

/**
 * The spacing scale, slug to the name an operator sees.
 *
 * The slugs are numbers because WordPress derives them from the step count and
 * writes them into post content; the names are t-shirt sizes because "L" is a
 * thing a person can choose between and `spacing--70` is not. One scale, named
 * once, offered by every control that spends spacing — block gap, page side
 * padding, section padding — so a site can be tightened or opened up by moving
 * several settings through the same vocabulary.
 *
 * @return array<string, string> Slug => display name, smallest first.
 */
function bridge_spacing_steps(): array
{
	return array(
		'20' => 'XS',
		'30' => 'S',
		'40' => 'M',
		'50' => 'L',
		'60' => 'XL',
		'70' => '2XL',
		'80' => '3XL',
	);
}

/**
 * The grounds a card can sit on, and what it is painted when it does.
 *
 * A card has no single background, because the band behind it does not. The
 * four entries here are the four grounds this theme actually paints — the page
 * itself, and the three section skins — so "the card background" is four
 * colours an operator sets once, not one colour that is wrong on three of
 * them. A card resolves its own by inheriting `--bridge-card-bg`, which the
 * skin sets; the default is `light`.
 *
 * `ground` and `text` name the palette slugs the band wears, which is what
 * lets the options page draw each card on its real ground rather than on a
 * guess. They mirror bridge_section_skins() and have to stay in step with it.
 *
 * Deliberately *not* palette slugs of their own. Adding these to the palette
 * would put them in every colour picker in the editor, where a card colour is
 * not a thing anyone should be painting a paragraph with — and palette slugs
 * are written into post content as class names, so they could never be taken
 * back. These are read only by abstracts/_card.scss.
 *
 * The defaults are literals rather than derived from the palette: a card is a
 * step away from its ground in a direction only a designer can choose, and a
 * formula that lightened every ground by a fixed amount would be wrong on at
 * least one of them. They are a starting point, and every one is editable.
 *
 * @return array<string, array<string, string>>
 */
function bridge_card_grounds(): array
{
	return array(
		'light'   => array(
			'label'   => __('Light card', 'bridge'),
			'ground'  => 'background',
			'text'    => 'text',
			'default' => '#f5f5f4',
		),
		'surface' => array(
			'label'   => __('Surface card', 'bridge'),
			'ground'  => 'surface',
			'text'    => 'text',
			'default' => '#ffffff',
		),
		'primary' => array(
			'label'   => __('Primary card', 'bridge'),
			'ground'  => 'primary',
			// The Inverted skin's foreground. A card on this ground inherits
			// it, which is the whole reason the card colour has to be dark.
			'text'    => 'background',
			'default' => '#1e293b',
		),
		'accent'  => array(
			'label'   => __('Accent card', 'bridge'),
			'ground'  => 'accent',
			'text'    => 'text',
			'default' => '#ffffff',
		),
	);
}

/**
 * The card grounds as a list, for the options page.
 *
 * @return array<int, array<string, string>>
 */
function bridge_card_ground_choices(): array
{
	$choices = array();

	foreach (bridge_card_grounds() as $key => $entry) {
		$choices[] = array(
			'key'    => (string) $key,
			'label'  => (string) $entry['label'],
			'ground' => (string) $entry['ground'],
			'text'   => (string) $entry['text'],
		);
	}

	return $choices;
}

/**
 * The card shadow presets, slug to its two states.
 *
 * Named steps rather than a free-text box, for the same reason the spacing
 * scale offers XS through 3XL: a box-shadow is four numbers and a colour, and
 * an operator asked to type one produces either the default back or something
 * that does not match the other five cards on the page. Four steps is the
 * whole useful range — off, and three degrees of lift.
 *
 * `hover` is the raised state, spent by the one card that is itself a link.
 * Kept beside the resting value rather than derived from it, because a shadow
 * that lifts is not the resting one scaled — it moves further and softens.
 *
 * Filterable, so a client build with a house elevation scale can name its own
 * without a theme edit. The slugs are what the token record stores, so a
 * filter that renames one strands the sites already using it.
 *
 * @return array<string, array<string, string>>
 */
function bridge_card_shadows(): array
{
	return (array) apply_filters(
		'bridge_card_shadows',
		array(
			'none'   => array(
				'name'   => __('None', 'bridge'),
				'shadow' => 'none',
				'hover'  => 'none',
			),
			'soft'   => array(
				'name'   => __('Soft', 'bridge'),
				'shadow' => '0 1px 3px rgba(0, 0, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.06)',
				'hover'  => '0 4px 12px rgba(0, 0, 0, 0.1), 0 12px 24px rgba(0, 0, 0, 0.08)',
			),
			'medium' => array(
				'name'   => __('Medium', 'bridge'),
				'shadow' => '0 2px 6px rgba(0, 0, 0, 0.1), 0 8px 20px rgba(0, 0, 0, 0.08)',
				'hover'  => '0 6px 16px rgba(0, 0, 0, 0.12), 0 18px 36px rgba(0, 0, 0, 0.1)',
			),
			'strong' => array(
				'name'   => __('Strong', 'bridge'),
				'shadow' => '0 4px 10px rgba(0, 0, 0, 0.12), 0 14px 32px rgba(0, 0, 0, 0.12)',
				'hover'  => '0 8px 20px rgba(0, 0, 0, 0.16), 0 24px 48px rgba(0, 0, 0, 0.14)',
			),
		)
	);
}

/**
 * The font-size slugs a card heading may be set to.
 *
 * The site's own scale, not a list of lengths. `bridge_compile_font_sizes()`
 * builds five fluid steps from the base size and the scale ratio, and a card
 * heading is one of them — so a client who picks a more dramatic ratio moves
 * their card headings with everything else, and a card can never be the one
 * piece of type on the site that is off the scale.
 *
 * Ordered small to large, because the control offers them in that order and a
 * serialised JSON object carries no promise of key order.
 *
 * @return array<int, string>
 */
function bridge_font_size_slugs(): array
{
	return array('small', 'medium', 'large', 'x-large', 'xx-large');
}

/**
 * The crops a card's image may be cut to.
 *
 * Named ratios rather than a free-text `aspect-ratio`, for the reason the
 * shadow presets give: an operator asked to type one produces either the
 * default back or a number that makes every photograph on the site a different
 * shape. These four are the crops photography is actually shot and delivered
 * in.
 *
 * `value` is a CSS `aspect-ratio`, published as a custom property and read by
 * the card's image frame. Portrait is absent on purpose — its image is a
 * circle, and a circle has one ratio.
 *
 * @return array<string, array<string, string>>
 */
function bridge_card_ratios(): array
{
	return (array) apply_filters(
		'bridge_card_ratios',
		array(
			'16-9' => array('name' => __('Widescreen (16:9)', 'bridge'), 'value' => '16 / 9'),
			'3-2'  => array('name' => __('Photograph (3:2)', 'bridge'), 'value' => '3 / 2'),
			'4-3'  => array('name' => __('Classic (4:3)', 'bridge'), 'value' => '4 / 3'),
			'1-1'  => array('name' => __('Square (1:1)', 'bridge'), 'value' => '1 / 1'),
		)
	);
}

/**
 * The ratios as a list, for the options page.
 *
 * @return array<int, array<string, string>>
 */
function bridge_card_ratio_choices(): array
{
	$choices = array();

	foreach (bridge_card_ratios() as $slug => $entry) {
		$choices[] = array(
			'slug'  => (string) $slug,
			'name'  => (string) ($entry['name'] ?? $slug),
			'value' => (string) ($entry['value'] ?? '16 / 9'),
		);
	}

	return $choices;
}

/**
 * How large a Portrait card's avatar is drawn.
 *
 * Three steps rather than a slider, because the number is not one number: the
 * avatar's width is a `min()` of a percentage of the card and a fixed ceiling,
 * and the two have to move together. Set only the percentage and a single card
 * in a one-column grid becomes a portrait the height of the viewport; set only
 * the ceiling and the avatar stops filling a wide card.
 *
 * `fraction` is the same percentage as a number, and it is not decoration: it
 * is what the block spends on the image's `sizes` attribute, so the browser
 * fetches a file the size of the slot rather than the size of the column. The
 * two must stay in step — see the note in the Cards block's render.php.
 *
 * @return array<string, array<string, mixed>>
 */
function bridge_card_avatar_sizes(): array
{
	return (array) apply_filters(
		'bridge_card_avatar_sizes',
		array(
			's' => array(
				'name'     => __('Small', 'bridge'),
				'width'    => 'min(56%, 11rem)',
				'fraction' => 0.56,
			),
			'm' => array(
				'name'     => __('Medium', 'bridge'),
				'width'    => 'min(72%, 14rem)',
				'fraction' => 0.72,
			),
			'l' => array(
				'name'     => __('Large', 'bridge'),
				'width'    => 'min(88%, 17rem)',
				'fraction' => 0.88,
			),
		)
	);
}

/**
 * The avatar sizes as a list, for the options page.
 *
 * @return array<int, array<string, mixed>>
 */
function bridge_card_avatar_size_choices(): array
{
	$choices = array();

	foreach (bridge_card_avatar_sizes() as $slug => $entry) {
		$choices[] = array(
			'slug'  => (string) $slug,
			'name'  => (string) ($entry['name'] ?? $slug),
			'width' => (string) ($entry['width'] ?? 'min(72%, 14rem)'),
		);
	}

	return $choices;
}

/**
 * The three card styles, and which settings each one has.
 *
 * The `bridge/cards` block draws one of three shapes, and they do not take the
 * same settings: Summary and Tile crop a photograph to a ratio, Portrait draws
 * a circle and takes a size instead. Rather than give every style every field
 * and hide two of them, each style declares the fields it has and the
 * sanitiser, the compiler and the options page all walk this list.
 *
 * That is what makes a fourth style an entry here rather than an edit in five
 * files.
 *
 * ---- Why these are per style and not per ground ----------------------------
 *
 * Cards already have a per-ground setting — their background, which has to
 * change with the band because contrast does. Nothing here does. A heading is
 * the same size on a white page and a dark one, because size is hierarchy and
 * ground is contrast; splitting them per ground would give one card four
 * heading sizes with no design reason for any of them.
 *
 * The other half of that rule is the one abstracts/_card.scss states: a card
 * never names its own text colour, it inherits the band's. So the grounds get
 * colour and the styles get everything else, and neither list has to grow when
 * the other does.
 *
 * @return array<string, array<string, mixed>>
 */
function bridge_card_styles(): array
{
	return (array) apply_filters(
		'bridge_card_styles',
		array(
			'summary'  => array(
				'name'        => __('Summary', 'bridge'),
				'description' => __('A photograph, a heading and a few lines of the post itself. For a list of things to read.', 'bridge'),
				'fields'      => array('heading', 'ratio'),
				'heading'     => 'large',
				'ratio'       => '16-9',
			),
			'tile'     => array(
				'name'        => __('Tile', 'bridge'),
				'description' => __('A large heading over a photograph, with a chip carrying the post’s “distance” field. For places rather than articles.', 'bridge'),
				'fields'      => array('heading', 'ratio'),
				'heading'     => 'x-large',
				'ratio'       => '16-9',
			),
			'portrait' => array(
				'name'        => __('Portrait', 'bridge'),
				'description' => __('A circular photograph arching over a panel, a name, the post’s “subtitle” field, and a button. For people.', 'bridge'),
				'fields'      => array('heading', 'avatar'),
				'heading'     => 'large',
				'avatar'      => 'm',
			),
		)
	);
}

/**
 * Which option list a card-style field is chosen from.
 *
 * One map so the sanitiser, the REST payload and the options page cannot
 * disagree about what a field may hold. Keyed by field name; every field named
 * in a style's `fields` must appear here or it is dropped.
 *
 * @return array<string, array<int, string>>
 */
function bridge_card_style_options(): array
{
	return array(
		'heading' => bridge_font_size_slugs(),
		'ratio'   => array_keys(bridge_card_ratios()),
		'avatar'  => array_keys(bridge_card_avatar_sizes()),
	);
}

/**
 * The card styles as a list, for the options page.
 *
 * @return array<int, array<string, mixed>>
 */
function bridge_card_style_choices(): array
{
	$choices = array();

	foreach (bridge_card_styles() as $slug => $entry) {
		$choices[] = array(
			'slug'        => (string) $slug,
			'name'        => (string) ($entry['name'] ?? $slug),
			'description' => (string) ($entry['description'] ?? ''),
			'fields'      => array_values((array) ($entry['fields'] ?? array())),
		);
	}

	return $choices;
}

/**
 * The shadow presets as a list, for the options page.
 *
 * A list rather than the map above, because the order is the meaning — the
 * control offers them from off to strongest — and JSON objects carry no
 * promise of key order once they have been through a serialiser.
 *
 * @return array<int, array<string, string>>
 */
function bridge_card_shadow_choices(): array
{
	$choices = array();

	foreach (bridge_card_shadows() as $slug => $entry) {
		$choices[] = array(
			'slug'   => (string) $slug,
			'name'   => (string) ($entry['name'] ?? $slug),
			'shadow' => (string) ($entry['shadow'] ?? 'none'),
			'hover'  => (string) ($entry['hover'] ?? 'none'),
		);
	}

	return $choices;
}

/**
 * The three button skins, and the geometry each one is.
 *
 * A skin is the *shape* of every button on the site — corner, padding,
 * tracking, how it answers a pointer — and it is one choice, not a set of
 * them. Offering an operator eleven properties would produce a button no
 * designer drew; offering three finished designs produces one of three that
 * were.
 *
 * Colour is deliberately absent from this list. What a button is painted
 * depends on the band it lands in, which is a separate question answered per
 * ground in bridge_button_grounds() — so a skin can be swapped without
 * revisiting four colour decisions, and a colour can be moved without
 * redrawing the button.
 *
 * Every value is CSS, published as a `--wp--custom--button--*` property, so
 * the front end, the editor and the options preview all draw the same button
 * from the same numbers.
 *
 *   radius         Corner. `edge` is 0 on purpose: a squared button is the
 *                  one shape the other two cannot be mistaken for.
 *   paddingBlock   Air above and below the label. The floor under the tap
 *                  target is enforced separately — see `minSize` in
 *                  bridge_compile_theme_json().
 *   paddingInline  Air either side.
 *   weight         Label weight. 600 throughout: a button is an action, and
 *                  500 reads as a link that happens to have a box.
 *   transform      `uppercase` on `edge` alone, where the tracking is set to
 *                  match — uppercase at normal tracking is a wall.
 *   letterSpacing  Tracking. Positive only where the case demands it.
 *   borderWidth    The boundary. Filled buttons carry one too, in their own
 *                  fill colour, so the two styles are exactly the same size
 *                  and a fill that needs a visible edge (WCAG 1.4.11) can be
 *                  given one without the button changing dimensions.
 *   shadow         Resting elevation.
 *   shadowHover    Elevation under the pointer.
 *   lift           Vertical nudge under the pointer. Suppressed under
 *                  `prefers-reduced-motion`.
 *   sweep          Height of the rule that draws itself under the label on
 *                  hover. 0 on the skins that answer with fill and lift
 *                  instead, which costs them nothing: a 0-height bar paints
 *                  nothing.
 *   fill           How far the fill shades on hover, 0–1 of the distance to
 *                  black or white. Not CSS — the shading happens server-side
 *                  so the hover colour is a known hex whose contrast can be
 *                  measured. See bridge_button_schemes().
 *
 * Filterable so a client build can ship a fourth. The slugs are stored in the
 * token record, so a filter that renames one strands the sites using it.
 *
 * @return array<string, array<string, string|float>>
 */
function bridge_button_skins(): array
{
	return (array) apply_filters(
		'bridge_button_skins',
		array(
			'solid'   => array(
				'name'          => __('Solid', 'bridge'),
				'description'   => __('A softly rounded filled button that lifts and deepens under the pointer. The safe, contemporary default — at home on a corporate site and on a shop.', 'bridge'),
				'radius'        => '6px',
				'paddingBlock'  => '0.85rem',
				'paddingInline' => '1.65rem',
				'weight'        => '600',
				'transform'     => 'none',
				'letterSpacing' => '0',
				'borderWidth'   => '2px',
				'shadow'        => 'none',
				'shadowHover'   => '0 6px 16px rgba(0, 0, 0, 0.16)',
				'lift'          => '-2px',
				'sweep'         => '0px',
				'fill'          => 0.12,
			),
			'edge'    => array(
				'name'          => __('Edge', 'bridge'),
				'description'   => __('Square corners, small uppercase label, wide tracking. A rule draws itself under the label on hover as the fill deepens. Editorial and architectural — the skin for a brand that does not want a rounded anything.', 'bridge'),
				// The one skin with no corner radius at all.
				'radius'        => '0',
				'paddingBlock'  => '0.9rem',
				'paddingInline' => '1.75rem',
				'weight'        => '600',
				'transform'     => 'uppercase',
				'letterSpacing' => '0.08em',
				'borderWidth'   => '2px',
				'shadow'        => 'none',
				// Flat by design. A square button that lifts reads as a tile
				// that came loose.
				'shadowHover'   => 'none',
				'lift'          => '0',
				'sweep'         => '2px',
				'fill'          => 0.18,
			),
			'pill'    => array(
				'name'          => __('Pill', 'bridge'),
				'description'   => __('Fully rounded with generous side padding and a resting shadow, rising under the pointer. Friendly and app-like — the skin for consumer and service brands.', 'bridge'),
				// Far past half the height of any button this theme draws, so
				// the ends stay true semicircles at every font size.
				'radius'        => '999px',
				'paddingBlock'  => '0.9rem',
				'paddingInline' => '2rem',
				'weight'        => '600',
				'transform'     => 'none',
				'letterSpacing' => '0.01em',
				'shadow'        => '0 1px 2px rgba(0, 0, 0, 0.12), 0 4px 10px rgba(0, 0, 0, 0.08)',
				'borderWidth'   => '2px',
				'shadowHover'   => '0 4px 10px rgba(0, 0, 0, 0.16), 0 12px 24px rgba(0, 0, 0, 0.12)',
				'lift'          => '-3px',
				'sweep'         => '0px',
				'fill'          => 0.12,
			),
		)
	);
}

/**
 * The skins as a list, for the options page.
 *
 * A list rather than the map, for the reason bridge_card_shadow_choices()
 * gives: the order is the meaning, and a serialised object does not promise to
 * keep it.
 *
 * @return array<int, array<string, string|float>>
 */
function bridge_button_skin_choices(): array
{
	$choices = array();

	foreach (bridge_button_skins() as $slug => $entry) {
		$choices[] = array('slug' => (string) $slug) + $entry;
	}

	return $choices;
}

/**
 * The grounds a button can sit on, and what fills it on each.
 *
 * The same four grounds cards answer for — the page itself and the three
 * section skins — because they are the four backgrounds this theme actually
 * paints. A button cannot name its own fill for the same reason a card cannot
 * name its own surface: the primary-coloured button that anchors a white page
 * is invisible on an Inverted band.
 *
 * `ground` and `text` are the palette slugs the band wears, and they mirror
 * bridge_section_skins() and bridge_card_grounds() — all three have to stay in
 * step. `fill` is the palette slug the filled button defaults to there.
 *
 * The operator picks the fill and nothing else. Every other colour in the
 * scheme — the label, both hover colours, the boundary, the focus ring — is
 * computed from that choice in bridge_button_schemes(), because each of them
 * has one right answer given a fill and a ground, and a control that let
 * someone choose the wrong one would be a control for failing an audit.
 *
 * @return array<string, array<string, string>>
 */
function bridge_button_grounds(): array
{
	return array(
		'default'  => array(
			'label'  => __('Default', 'bridge'),
			'ground' => 'background',
			'text'   => 'text',
			'fill'   => 'primary',
		),
		'surface'  => array(
			'label'  => __('Surface', 'bridge'),
			'ground' => 'surface',
			'text'   => 'text',
			'fill'   => 'primary',
		),
		'accent'   => array(
			'label'  => __('Accent', 'bridge'),
			'ground' => 'accent',
			'text'   => 'text',
			// The accent band is already the loudest thing on the page, so its
			// button answers with weight rather than more colour.
			'fill'   => 'primary',
		),
		'inverted' => array(
			'label'  => __('Inverted', 'bridge'),
			'ground' => 'primary',
			// The Inverted skin's foreground, which the band sets and
			// everything inside it inherits.
			'text'   => 'background',
			// A dark button on a dark band is a hole. Inverted, it becomes the
			// brightest thing in the section, which is what a primary action
			// on a dark band should be.
			'fill'   => 'background',
		),
	);
}

/**
 * The grounds as a list, for the options page.
 *
 * @return array<int, array<string, string>>
 */
function bridge_button_ground_choices(): array
{
	$choices = array();

	foreach (bridge_button_grounds() as $key => $entry) {
		$choices[] = array('key' => (string) $key) + $entry;
	}

	return $choices;
}

/**
 * Resolve every button colour, on every ground, from the four fill choices.
 *
 * One function, because these colours are a system rather than a list: the
 * hover fill is the resting fill shaded, the label is whichever palette colour
 * is legible on the fill, the hover label is re-checked against the shaded
 * fill, and the boundary only appears when the fill is too close to the band
 * behind it to have an edge of its own. Computed together, they cannot
 * disagree; computed in four stylesheets, they did.
 *
 * What each scheme guarantees, and the criterion it is guaranteeing:
 *
 *   1.4.3  Contrast (minimum) — the label is picked by ratio against the fill
 *          it sits on, from the palette first and black or white as a
 *          backstop. Every colour reaches at least 4.58:1 against one of
 *          those two, so a label that fails is not reachable from here.
 *   1.4.11 Non-text contrast — a fill within 3:1 of its own band would have
 *          no discernible edge, so it is given a border in the band's
 *          foreground, which by construction contrasts with both.
 *   2.4.11 Focus not obscured / focus appearance — the ring is the band's
 *          foreground, offset far enough to clear the button's own boundary.
 *
 * The audit alongside each scheme is the arithmetic itself, so the options
 * page can show the ratios rather than assert that they are fine, and so a
 * client asking "does this pass" gets a number.
 *
 * @param array<string, mixed> $tokens A sanitised token set.
 * @return array<string, array<string, mixed>> Ground key => colours + audit.
 */
function bridge_button_schemes(array $tokens): array
{
	$palette = $tokens['brand']['palette'];
	$skins   = bridge_button_skins();
	$skin    = $skins[$tokens['buttons']['skin']] ?? reset($skins);
	$shade   = (float) ($skin['fill'] ?? 0.12);

	$hex = static function (string $slug) use ($palette): string {
		return (string) ($palette[$slug]['color'] ?? '#000000');
	};

	// The two palette colours a label is allowed to be, in preference order.
	// Offered before black and white so a brand's own near-white beats #ffffff
	// when both are legible.
	$labels = array($hex('background'), $hex('text'));

	$schemes = array();

	foreach (bridge_button_grounds() as $key => $entry) {
		$ground     = $hex($entry['ground']);
		$foreground = $hex($entry['text']);
		$fill       = $hex((string) ($tokens['buttons']['colors'][$key] ?? $entry['fill']));

		$hover_fill  = bridge_shade_hex($fill, $shade);
		$label       = bridge_readable_on($fill, $labels);
		// The resting label first, so a hover state only changes colour when
		// the shaded fill genuinely stopped carrying it.
		$hover_label = bridge_readable_on($hover_fill, array_merge(array($label), $labels));

		$edge       = bridge_contrast_ratio($fill, $ground);
		$hover_edge = bridge_contrast_ratio($hover_fill, $ground);

		/**
		 * The band's own foreground, promoted if it cannot do the job.
		 *
		 * These three — the border a fill is given when it has no edge of its
		 * own, the focus ring, and the secondary button — were the band's
		 * foreground outright, on the reasoning that a colour legible enough
		 * to be the band's text is legible enough to draw a line in.
		 *
		 * That holds for a palette anyone would design and fails for one the
		 * sanitiser will nonetheless accept. A brand of mid-greys puts its
		 * text at 1.01:1 against its own background; a brand that recolours
		 * `text` for a dark background leaves it at 1.95:1 on the Accent band.
		 * In both, the border drawn to satisfy 1.4.11 was as invisible as the
		 * fill it was covering for, and the focus ring with it.
		 *
		 * So each is asked for at the threshold it actually has to meet — 3:1
		 * for a boundary, 4.5:1 for the secondary button's label — and falls
		 * back to black or white when the palette cannot supply it, which
		 * always clears both. On a palette that was already fine, every one of
		 * these is the foreground, unchanged.
		 */
		$boundary = bridge_readable_on($ground, array($foreground), 3.0);
		$ghost    = bridge_readable_on($ground, array($foreground), 4.5);

		// A boundary only where the fill has not got one.
		$border       = $edge >= 3.0 ? $fill : $boundary;
		$hover_border = $hover_edge >= 3.0 ? $hover_fill : $boundary;

		$schemes[$key] = array(
			'bg'          => strtolower($fill),
			'fg'          => strtolower($label),
			'hoverBg'     => strtolower($hover_fill),
			'hoverFg'     => strtolower($hover_label),
			'border'      => strtolower($border),
			'hoverBorder' => strtolower($hover_border),
			// The secondary button. Transparent, carrying the band's own
			// foreground as its label and boundary — the one treatment legible
			// on all four grounds — and inverting into the band on hover,
			// which is a change of state no colour blindness can miss.
			'ghost'       => strtolower($ghost),
			'ghostHover'  => strtolower($ground),
			// Focus. Offset clear of the button's own edge, so the ring is
			// measured against the band rather than against the button.
			'ring'        => strtolower($boundary),
			// The arithmetic, for the options screen to show and for anyone
			// who has to answer "does this pass" with a number rather than a
			// reassurance. `fill` is the ratio of the button's own colour
			// against its band and `boundary` the ratio of whatever actually
			// draws its edge — the same figure until the fill is too close to
			// the band to have an edge, at which point the border it was given
			// is what 1.4.11 is measuring.
			'audit'       => array(
				'label'      => bridge_contrast_ratio($fill, $label),
				'hoverLabel' => bridge_contrast_ratio($hover_fill, $hover_label),
				'fill'       => $edge,
				'boundary'   => $edge >= 3.0 ? $edge : bridge_contrast_ratio($border, $ground),
				'ghost'      => bridge_contrast_ratio($ground, $ghost),
				'ring'       => bridge_contrast_ratio($ground, $boundary),
				// True when the fill could not be its own edge and was given
				// one.
				'bordered'   => $edge < 3.0,
			),
		);
	}

	return $schemes;
}

/**
 * The valid range or option set for every numeric and enumerated token.
 *
 * One source of truth, consumed by both the sanitiser and the REST route that
 * feeds the options page. Split across two definitions, a slider would sooner
 * or later offer a value the server silently clamps — which reads to the
 * operator as the page ignoring them.
 *
 * @return array<string, array<string, array<string, mixed>>>
 */
function bridge_token_constraints(): array
{
	return array(
		'typography' => array(
			// Below 0.75rem body copy stops being readable; above 1.5rem the
			// fluid clamps at the top of the scale start to overlap.
			'baseSize'          => array('min' => 0.75, 'max' => 1.5, 'step' => 0.0625, 'unit' => 'rem'),
			// Below ~1.05 the scale collapses into one size; above 2.0 an h1
			// dwarfs a phone viewport even after fluid compression.
			'scaleRatio'        => array('min' => 1.05, 'max' => 2.0, 'step' => 0.005),
			'bodyLineHeight'    => array('min' => 1.1, 'max' => 2.2, 'step' => 0.05),
			'headingLineHeight' => array('min' => 0.9, 'max' => 1.8, 'step' => 0.05),
			'headingWeight'     => array('options' => array('300', '400', '500', '600', '700', '800', '900')),
			'headingCase'       => array('options' => array('none', 'uppercase')),
		),
		'icons'      => array(
			'weight' => array('options' => array('regular', 'bold')),
		),
		'buttons'    => array(
			'skin' => array('options' => array_keys(bridge_button_skins())),
			// The fill an operator may choose per ground. The whole palette,
			// because every slug in it is a legitimate button on some ground —
			// and the ones that would be illegible are made legible by the
			// scheme rather than forbidden here.
			'fill' => array('options' => array_keys(bridge_palette_slugs())),
		),
		'cards'      => array(
			// The same spacing vocabulary every other padding control speaks,
			// so a site tightened a step tightens its cards with everything
			// else rather than needing a number found by trial.
			'padding' => array('options' => bridge_spacing_slugs()),
			// 0 is a legitimate look — square cards are a design, not an
			// error. Past about 32px the corner starts eating the content of
			// a narrow card rather than framing it.
			'radius'  => array('min' => 0, 'max' => 32, 'step' => 1, 'unit' => 'px'),
			'shadow'  => array('options' => array_keys(bridge_card_shadows())),
			// The site's default excerpt length, in words, for every Cards
			// block that has not been given one of its own. Ten is about the
			// shortest run of prose that still reads as a sentence rather than
			// a fragment; past a hundred the card has stopped summarising and
			// started reproducing.
			'excerpt' => array('min' => 10, 'max' => 100, 'step' => 1),
		),
		'header'     => array(
			// Every layout stacks or rows the same two elements; none puts the
			// menu in a fixed centre column, which would cap how many items it
			// can hold as a client's services grow.
			'layout'       => array('options' => array('left', 'centre', 'two-row')),
			'background'   => array('options' => array('solid', 'transparent')),
			'contrast'     => array('options' => array('auto', 'light', 'dark')),
			'logoHeight'   => array('min' => 16, 'max' => 120, 'step' => 2, 'unit' => 'px'),
			// 0 is a header whose logo touches the edges of its ground — flush
			// is a legitimate look, so it is a legitimate value. Above ~80 the
			// bar stops reading as a header and starts reading as a section.
			'paddingBlock' => array('min' => 0, 'max' => 80, 'step' => 2, 'unit' => 'px'),
		),
		'footer'     => array(
			'style' => array('options' => array('simple', 'columns')),
		),
		'layout'     => array(
			'contentSize'      => array('min' => 320, 'max' => 1600, 'step' => 10, 'unit' => 'px'),
			'wideSize'         => array('min' => 480, 'max' => 2400, 'step' => 10, 'unit' => 'px'),
			'spacingBase'      => array('min' => 0.5, 'max' => 4.0, 'step' => 0.25, 'unit' => 'rem'),
			'spacingIncrement' => array('min' => 1.1, 'max' => 2.0, 'step' => 0.05),
			'blockGap'         => array('options' => bridge_spacing_slugs()),
			'rootPadding'      => array('options' => bridge_spacing_slugs()),
			'sectionPadding'   => array('options' => bridge_spacing_slugs()),
		),
	);
}

/**
 * Complete fallback token set.
 *
 * Mirrors the shipped design/tokens.json, but lives in code so the theme can
 * never be left without a valid design system.
 *
 * @return array<string, mixed>
 */
function bridge_token_defaults(): array
{
	$palette = array();
	foreach (bridge_palette_slugs() as $slug => $name) {
		$palette[$slug] = array(
			'color' => '#000000',
			'name'  => $name,
		);
	}

	$palette['primary']['color']    = '#0F172A';
	$palette['secondary']['color']  = '#2563EB';
	$palette['accent']['color']     = '#F59E0B';
	$palette['background']['color'] = '#FFFFFF';
	$palette['surface']['color']    = '#F5F5F4';
	$palette['text']['color']       = '#1F2937';

	// Each style's own defaults, taken from the style list rather than repeated
	// here — the list is where a style says what it is, and a second copy of
	// the same three values is a second copy to forget to update.
	$card_styles = array();
	foreach (bridge_card_styles() as $slug => $entry) {
		$style = array();

		foreach ((array) ($entry['fields'] ?? array()) as $field) {
			if (isset($entry[$field])) {
				$style[$field] = $entry[$field];
			}
		}

		$card_styles[$slug] = $style;
	}

	$card_colors = array();
	foreach (bridge_card_grounds() as $key => $entry) {
		$card_colors[$key] = $entry['default'];
	}

	$button_colors = array();
	foreach (bridge_button_grounds() as $key => $entry) {
		$button_colors[$key] = $entry['fill'];
	}

	return array(
		'brand'      => array(
			'palette' => $palette,
		),
		'typography' => array(
			'fontSet'           => 'system',
			'googleFonts'       => false,
			'googleHeading'     => '',
			'googleBody'        => '',
			'baseSize'          => 1.0,
			'scaleRatio'        => 1.5,
			'headingWeight'     => '600',
			'headingCase'       => 'none',
			'bodyLineHeight'    => 1.6,
			'headingLineHeight' => 1.2,
		),
		'icons'      => array(
			'weight' => 'regular',
		),
		// One shape for every button on the site, and one fill per ground.
		// The defaults are the skin closest to what the theme drew before this
		// was a setting, and each ground's own preferred fill, so a site that
		// never opens the control keeps the buttons it had.
		'buttons'    => array(
			'skin'   => 'solid',
			'colors' => $button_colors,
		),
		// What every card block draws: the post cards, downloads, feature
		// panels, price cards and testimonials. One set of three values rather
		// than five stylesheets each choosing its own, which is what they did
		// before this was a setting. The defaults are what they had settled
		// on, so a site that never opens the control keeps the look it had.
		'cards'      => array(
			'padding' => '40',
			'radius'  => 6,
			'shadow'  => 'soft',
			'colors'  => $card_colors,
			// The excerpt length a Cards block uses when it has not been given
			// one. Twenty is what the block's own default was, so a site that
			// never opens the control keeps the cards it had.
			'excerpt' => 20,
			'styles'  => $card_styles,
		),
		'header'     => array(
			'layout'          => 'left',
			'topBar'          => false,
			// 0 means "let core pick" — a fresh site has no menus yet, and a
			// header that renders nothing until someone visits a settings page
			// is worse than one that guesses.
			'menus'           => array('primary' => 0, 'utility' => 0),
			'background'      => 'solid',
			'backgroundColor' => 'background',
			'contrast'        => 'auto',
			'sticky'          => false,
			'border'          => false,
			// The air above and below the logo at full width, in pixels. Near
			// the 0.67rem the header used before this was a setting, so a site
			// that never opens the control keeps the height it had.
			'paddingBlock'    => 12,
			// Two images of one wordmark: `id` is the dark logo, drawn for a
			// light ground, and `lightId` the light one for a dark ground.
			// Either may be 0 — a site with a single logo uses it everywhere.
			'logo'            => array('id' => 0, 'lightId' => 0, 'height' => 40),
			'cta'             => array('enabled' => false, 'label' => '', 'url' => ''),
		),
		'footer'     => array(
			'style' => 'simple',
		),
		// Deviations from the theme's curated block set, not the set itself.
		// Storing the whole list would freeze it: a block added by a later
		// theme release would arrive switched off, because it could not be in
		// a list written before it existed.
		'blocks'     => array(
			'enabled'  => array(),
			'disabled' => array(),
		),
		'layout'     => array(
			'contentSize'      => 720,
			'wideSize'         => 1200,
			'spacingBase'      => 1.5,
			'spacingIncrement' => 1.5,
			'blockGap'         => '40',
			'rootPadding'      => '40',
			// The air above and below a section. Two steps above the page's
			// side padding: vertical rhythm carries the separation between one
			// section and the next, where the horizontal gutter only has to
			// keep text off the edge of the screen.
			'sectionPadding'   => '70',
		),
		// Not design: what WordPress serves *alongside* the pages. Grouped
		// apart from the visual tokens because nothing here compiles into
		// theme.json — these values are read by inc/wp-clean.php, which only
		// ever removes output.
		'site'       => array(
			'feeds' => false,
		),
	);
}

/**
 * The curated font sets, keyed by slug.
 *
 * @return array<string, array<string, mixed>>
 */
function bridge_font_sets(): array
{
	static $sets = null;

	if (null !== $sets) {
		return $sets;
	}

	$sets = array();
	$path = get_theme_file_path('design/font-sets.json');

	if (file_exists($path)) {
		$data = wp_json_file_decode($path, array('associative' => true));

		if (is_array($data)) {
			foreach ($data as $slug => $set) {
				// Skip the "$comment" key and any malformed entry.
				if (! is_array($set) || empty($set['families']) || ! is_array($set['families'])) {
					continue;
				}

				$sets[(string) $slug] = $set;
			}
		}
	}

	// A set named `system` is the guaranteed fallback for an invalid choice, so
	// synthesise one if the manifest is missing or unreadable.
	if (! isset($sets['system'])) {
		$sets['system'] = array(
			'name'     => 'System',
			'families' => array(
				'sans'  => "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
				'serif' => "Georgia, 'Times New Roman', Times, serif",
				'mono'  => 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
			),
		);
	}

	return $sets;
}

/**
 * The committed per-client seed, or an empty array if none ships.
 *
 * @return array<string, mixed>
 */
function bridge_token_seed(): array
{
	static $seed = null;

	if (null !== $seed) {
		return $seed;
	}

	$seed = array();
	$path = get_theme_file_path('design/tokens.json');

	if (file_exists($path)) {
		$data = wp_json_file_decode($path, array('associative' => true));

		if (is_array($data)) {
			$seed = $data;
		}
	}

	return $seed;
}

/**
 * Recursively merge $overrides into $base, associative keys only.
 *
 * Unlike array_merge_recursive() this replaces scalars rather than collecting
 * them into arrays, which is what layering partial token overrides needs.
 *
 * A list — `blocks.disabled`, `blocks.enabled` — is one value, not a map of
 * positions, so it is replaced whole. Merging it by index would let a list
 * grow but never shrink: dropping a block from `disabled` would leave the
 * lower layer's entry sitting at the same index, and switching a block back on
 * would silently do nothing.
 *
 * @param array<string, mixed> $base      Lower-priority values.
 * @param array<string, mixed> $overrides Higher-priority values.
 * @return array<string, mixed>
 */
function bridge_merge_deep(array $base, array $overrides): array
{
	foreach ($overrides as $key => $value) {
		if (
			is_array($value)
			&& isset($base[$key])
			&& is_array($base[$key])
			&& ! array_is_list($value)
			&& ! array_is_list($base[$key])
		) {
			$base[$key] = bridge_merge_deep($base[$key], $value);
			continue;
		}

		$base[$key] = $value;
	}

	return $base;
}

/**
 * Runtime memo for the resolved token set.
 *
 * Kept in its own accessor so bridge_flush_tokens() can clear it — the
 * resolver may read tokens again later in the same request that saved them.
 *
 * @param array<string, mixed>|null $value Array to store, or null to read.
 * @param bool                      $clear Drop the stored value.
 * @return array<string, mixed>|null
 */
function bridge_tokens_memo(?array $value = null, bool $clear = false): ?array
{
	static $memo = null;

	if ($clear) {
		$memo = null;

		return null;
	}

	if (null !== $value) {
		$memo = $value;
	}

	return $memo;
}

/**
 * The resolved, sanitised, guaranteed-complete token set.
 *
 * @return array<string, mixed>
 */
function bridge_get_tokens(): array
{
	$memo = bridge_tokens_memo();

	if (null !== $memo) {
		return $memo;
	}

	$stored = get_option(BRIDGE_TOKENS_OPTION, array());
	$raw    = bridge_merge_deep(bridge_token_seed(), is_array($stored) ? $stored : array());

	$tokens = bridge_sanitize_tokens($raw);
	bridge_tokens_memo($tokens);

	return $tokens;
}

/**
 * Clamp a value into a numeric range, falling back when it isn't a number.
 *
 * @param mixed $value    Candidate.
 * @param float $min      Lower bound, inclusive.
 * @param float $max      Upper bound, inclusive.
 * @param float $fallback Used when $value is not numeric.
 */
function bridge_clamp_float($value, float $min, float $max, float $fallback): float
{
	if (! is_numeric($value)) {
		return $fallback;
	}

	return min($max, max($min, (float) $value));
}

/**
 * Clamp a token against its declared constraint.
 *
 * @param string $group    Token group: `typography` or `layout`.
 * @param string $key      Token key.
 * @param mixed  $value    Candidate.
 * @param float  $fallback Used when $value is not numeric.
 */
function bridge_clamp_token(string $group, string $key, $value, float $fallback): float
{
	$constraint = bridge_token_constraints()[$group][$key];

	return bridge_clamp_float($value, (float) $constraint['min'], (float) $constraint['max'], $fallback);
}

/**
 * Accept a token only if it is one of its declared options.
 *
 * @param string $group    Token group: `typography` or `layout`.
 * @param string $key      Token key.
 * @param mixed  $value    Candidate.
 * @param string $fallback Used when $value is not a valid option.
 */
function bridge_pick_token(string $group, string $key, $value, string $fallback): string
{
	$options = bridge_token_constraints()[$group][$key]['options'];

	return in_array((string) $value, $options, true) ? (string) $value : $fallback;
}

/**
 * The colour pairs the theme actually draws, and what each has to clear.
 *
 * A palette is not six independent choices. Six slugs produce a fixed set of
 * combinations, because the theme decides where each one lands: `text` on
 * `background` is every paragraph on the site, `background` on `primary` is
 * every word in an Inverted band, `secondary` on `background` is every link.
 * An operator picking a brand colour is picking one side of several pairs at
 * once, and until this existed the screen said nothing about the other side.
 *
 * Only pairs the theme genuinely renders are listed. `accent` on `surface`
 * would be a number about nothing — no rule in the stylesheet puts them
 * together — and a screen full of ratios for combinations that never happen
 * teaches an operator to ignore all of them.
 *
 * Every threshold here is 4.5:1, because every pair is body-sized text
 * (WCAG 2.2 §1.4.3). Headings are large text and would pass at 3:1, but they
 * are drawn in the same colour as the body on every one of these grounds, so
 * the stricter figure is the one that matters.
 *
 * @return array<int, array<string, mixed>>
 */
function bridge_palette_pairs(): array
{
	return array(
		array(
			'fg'    => 'text',
			'bg'    => 'background',
			'label' => __('Body text', 'bridge'),
			'on'    => __('on Background', 'bridge'),
			'min'   => 4.5,
			'note'  => __('Every paragraph on the site.', 'bridge'),
		),
		array(
			'fg'    => 'text',
			'bg'    => 'surface',
			'label' => __('Body text', 'bridge'),
			'on'    => __('on Surface', 'bridge'),
			'min'   => 4.5,
			'note'  => __('The Surface section skin, and any band painted with it.', 'bridge'),
		),
		array(
			'fg'    => 'text',
			'bg'    => 'accent',
			'label' => __('Body text', 'bridge'),
			'on'    => __('on Accent', 'bridge'),
			'min'   => 4.5,
			'note'  => __('The Accent skin keeps the dark foreground rather than inverting.', 'bridge'),
		),
		array(
			'fg'    => 'background',
			'bg'    => 'primary',
			'label' => __('Inverted text', 'bridge'),
			'on'    => __('on Primary', 'bridge'),
			'min'   => 4.5,
			'note'  => __('The Inverted skin: the light foreground on the brand’s dark ground.', 'bridge'),
		),
		array(
			'fg'    => 'secondary',
			'bg'    => 'background',
			'label' => __('Links', 'bridge'),
			'on'    => __('on Background', 'bridge'),
			'min'   => 4.5,
			'note'  => __('Every link in running text.', 'bridge'),
		),
		array(
			'fg'    => 'secondary',
			'bg'    => 'surface',
			'label' => __('Links', 'bridge'),
			'on'    => __('on Surface', 'bridge'),
			'min'   => 4.5,
			'note'  => __('The same links, inside a Surface band.', 'bridge'),
		),
	);
}

/**
 * Measure every pair the palette produces.
 *
 * The same arithmetic the buttons already report, pointed at the palette that
 * feeds them — which is where an inaccessible site actually starts. A button
 * scheme can rescue itself by picking a different label; body text cannot,
 * because the two colours in the pair are both the operator's choice.
 *
 * So this reports rather than repairs. There is no safe automatic fix: the
 * theme cannot darken a brand colour on the client's behalf, and a design
 * system that silently overrode the palette would be worse than one that says
 * plainly which pair fails and by how much.
 *
 * @param array<string, mixed> $tokens A sanitised token set.
 * @return array<int, array<string, mixed>>
 */
function bridge_palette_audit(array $tokens): array
{
	$palette = $tokens['brand']['palette'];
	$checks  = array();

	foreach (bridge_palette_pairs() as $pair) {
		$fg    = (string) ($palette[$pair['fg']]['color'] ?? '#000000');
		$bg    = (string) ($palette[$pair['bg']]['color'] ?? '#ffffff');
		$ratio = bridge_contrast_ratio($fg, $bg);

		$checks[] = array(
			'label' => $pair['label'],
			'on'    => $pair['on'],
			'note'  => $pair['note'],
			'fg'    => strtolower($fg),
			'bg'    => strtolower($bg),
			'ratio' => $ratio,
			'min'   => $pair['min'],
			'pass'  => $ratio >= $pair['min'],
		);
	}

	return $checks;
}

/**
 * Measure each card surface against the band it is painted on.
 *
 * Two questions per ground, and only one of them is a success criterion:
 *
 *   `text`  The band's foreground against the card, at 4.5:1. A card inherits
 *           its text from the band rather than naming its own, so this is
 *           1.4.3 for every word inside a card — and it is the check that
 *           catches the classic failure, a light card colour chosen on a light
 *           band while the words stay in the band's dark foreground.
 *
 *   `band`  The card against the band behind it. Reported as a number and
 *           deliberately *not* graded, because there is no threshold to grade
 *           it against: a card is meant to be a quiet step from its ground —
 *           the shipped Light card is 1.09:1 — and the shadow and the corner
 *           are what make it a card. Held to the 3:1 a control would owe, all
 *           four defaults fail, which would put four red badges on a design
 *           nothing is wrong with and teach an operator to ignore the two that
 *           mean something.
 *
 *           `flat` is the case that does mean something: a card the same
 *           colour as its band *and* carrying no shadow is not a quiet step,
 *           it is nothing at all.
 *
 * @param array<string, mixed> $tokens A sanitised token set.
 * @return array<int, array<string, mixed>>
 */
function bridge_card_audit(array $tokens): array
{
	$palette = $tokens['brand']['palette'];
	$colors  = $tokens['cards']['colors'];
	$lifted  = 'none' !== $tokens['cards']['shadow'];
	$checks  = array();

	foreach (bridge_card_grounds() as $key => $entry) {
		$card   = (string) ($colors[$key] ?? $entry['default']);
		$ground = (string) ($palette[$entry['ground']]['color'] ?? '#ffffff');
		$text   = (string) ($palette[$entry['text']]['color'] ?? '#000000');

		$on_card = bridge_contrast_ratio($card, $text);
		$on_band = bridge_contrast_ratio($card, $ground);

		$checks[] = array(
			'key'   => (string) $key,
			'label' => $entry['label'],
			'card'  => strtolower($card),
			'text'  => array(
				'ratio' => $on_card,
				'min'   => 4.5,
				'pass'  => $on_card >= 4.5,
			),
			'band'  => array(
				'ratio' => $on_band,
				// Indistinguishable from its ground, with nothing lifting it.
				'flat'  => $on_band < 1.05 && ! $lifted,
			),
		);
	}

	return $checks;
}

/**
 * A hex colour, or the fallback — for input that may be neither.
 *
 * `sanitize_hex_color()` has two ways of saying no, and only one of them is
 * `null`: an empty string it treats as "no colour" and hands straight back. A
 * plain `??` catches the null and not the empty string, so `{"color": ""}` —
 * which is what a cleared field, a hand-edited option or a partial import
 * produces — survived into the palette as an empty string. That compiles to a
 * custom property with no value, and reads as black to the contrast maths, so
 * the failure showed up as a button whose measured contrast was a fiction.
 *
 * Non-scalars are rejected before the cast rather than after: `(string)` on an
 * array is the literal "Array", which is not a colour and is not an error
 * either.
 *
 * @param mixed  $value    Candidate colour.
 * @param string $fallback Used when the candidate is not a usable colour.
 * @return string A `#rgb` or `#rrggbb` value.
 */
function bridge_hex_or($value, string $fallback): string
{
	$hex = is_scalar($value) ? sanitize_hex_color((string) $value) : null;

	return (is_string($hex) && '' !== $hex) ? $hex : $fallback;
}

/**
 * Reduce arbitrary input to a complete, valid token set.
 *
 * Total by design: anything missing, malformed or out of range is replaced
 * with the default rather than rejected, so a half-filled REST payload or a
 * hand-edited option can never produce a broken design system. This is the
 * only place token input is trusted — validate on write, not on read.
 *
 * @param array<string, mixed> $raw Candidate tokens, possibly partial.
 * @return array<string, mixed>
 */
function bridge_sanitize_tokens(array $raw): array
{
	$defaults = bridge_token_defaults();

	// ---- Brand palette ----------------------------------------------------
	$palette     = array();
	$raw_palette = isset($raw['brand']['palette']) && is_array($raw['brand']['palette'])
		? $raw['brand']['palette']
		: array();

	foreach (bridge_palette_slugs() as $slug => $default_name) {
		$entry = isset($raw_palette[$slug]) && is_array($raw_palette[$slug]) ? $raw_palette[$slug] : array();

		$name = isset($entry['name']) && is_scalar($entry['name'])
			? sanitize_text_field((string) $entry['name'])
			: '';

		$palette[$slug] = array(
			// A leading # and 3 or 6 hex digits, or the default — which is the
			// guarantee every piece of downstream contrast maths and every
			// line of compiled CSS is written against.
			'color' => bridge_hex_or(
				$entry['color'] ?? null,
				$defaults['brand']['palette'][$slug]['color']
			),
			'name'  => '' !== $name ? $name : $default_name,
		);
	}

	// ---- Typography -------------------------------------------------------
	$raw_type = isset($raw['typography']) && is_array($raw['typography']) ? $raw['typography'] : array();
	$dt       = $defaults['typography'];

	$font_set = isset($raw_type['fontSet']) ? sanitize_key((string) $raw_type['fontSet']) : '';
	if (! isset(bridge_font_sets()[$font_set])) {
		$font_set = $dt['fontSet'];
	}

	// Google families are validated against the curated catalogue, never
	// accepted as free text: the name is interpolated into an outbound URL and
	// becomes a directory name on disk.
	$google_on = ! empty($raw_type['googleFonts']);

	// Validated per role, not against the whole catalogue: the heading and
	// body lists differ, and a face chosen for the wrong job is a mistake
	// worth catching here rather than shipping to a client's homepage.
	$google_family = static function ($value, string $role) use ($google_on): string {
		$family = is_string($value) ? trim($value) : '';

		if (! $google_on || '' === $family || ! function_exists('bridge_google_families_for')) {
			return '';
		}

		return in_array($family, bridge_google_families_for($role), true) ? $family : '';
	};

	$typography = array(
		'fontSet'           => $font_set,
		'googleFonts'       => $google_on,
		'googleHeading'     => $google_family($raw_type['googleHeading'] ?? '', 'heading'),
		'googleBody'        => $google_family($raw_type['googleBody'] ?? '', 'body'),
		'baseSize'          => bridge_clamp_token('typography', 'baseSize', $raw_type['baseSize'] ?? null, (float) $dt['baseSize']),
		'scaleRatio'        => bridge_clamp_token('typography', 'scaleRatio', $raw_type['scaleRatio'] ?? null, (float) $dt['scaleRatio']),
		'headingWeight'     => bridge_pick_token('typography', 'headingWeight', $raw_type['headingWeight'] ?? '', $dt['headingWeight']),
		'headingCase'       => bridge_pick_token('typography', 'headingCase', $raw_type['headingCase'] ?? '', $dt['headingCase']),
		'bodyLineHeight'    => bridge_clamp_token('typography', 'bodyLineHeight', $raw_type['bodyLineHeight'] ?? null, (float) $dt['bodyLineHeight']),
		'headingLineHeight' => bridge_clamp_token('typography', 'headingLineHeight', $raw_type['headingLineHeight'] ?? null, (float) $dt['headingLineHeight']),
	);

	// ---- Layout -----------------------------------------------------------
	$raw_layout = isset($raw['layout']) && is_array($raw['layout']) ? $raw['layout'] : array();
	$dl         = $defaults['layout'];

	$content_size = (int) round(bridge_clamp_token('layout', 'contentSize', $raw_layout['contentSize'] ?? null, (float) $dl['contentSize']));
	$wide_size    = (int) round(bridge_clamp_token('layout', 'wideSize', $raw_layout['wideSize'] ?? null, (float) $dl['wideSize']));

	// A wide width narrower than the content width makes `alignwide` visibly
	// smaller than the default column — always a mistake, never a choice.
	if ($wide_size < $content_size) {
		$wide_size = $content_size;
	}

	$layout = array(
		'contentSize'      => $content_size,
		'wideSize'         => $wide_size,
		'spacingBase'      => bridge_clamp_token('layout', 'spacingBase', $raw_layout['spacingBase'] ?? null, (float) $dl['spacingBase']),
		'spacingIncrement' => bridge_clamp_token('layout', 'spacingIncrement', $raw_layout['spacingIncrement'] ?? null, (float) $dl['spacingIncrement']),
		'blockGap'         => bridge_pick_token('layout', 'blockGap', $raw_layout['blockGap'] ?? '', $dl['blockGap']),
		'rootPadding'      => bridge_pick_token('layout', 'rootPadding', $raw_layout['rootPadding'] ?? '', $dl['rootPadding']),
		'sectionPadding'   => bridge_pick_token('layout', 'sectionPadding', $raw_layout['sectionPadding'] ?? '', $dl['sectionPadding']),
	);

	// ---- Icons ------------------------------------------------------------
	$raw_icons = isset($raw['icons']) && is_array($raw['icons']) ? $raw['icons'] : array();

	$icons = array(
		'weight' => bridge_pick_token('icons', 'weight', $raw_icons['weight'] ?? '', $defaults['icons']['weight']),
	);

	// ---- Buttons ----------------------------------------------------------
	$raw_buttons = isset($raw['buttons']) && is_array($raw['buttons']) ? $raw['buttons'] : array();
	$db          = $defaults['buttons'];

	$raw_button_colors = isset($raw_buttons['colors']) && is_array($raw_buttons['colors']) ? $raw_buttons['colors'] : array();
	$button_fills      = array();

	// Palette slugs, not hex codes. A button fill has to be a colour the brand
	// already has — that is what keeps it tracking a palette change instead of
	// becoming a seventh colour hiding in a settings record. Keyed by ground
	// for the reason the card colours are: a payload missing one gets the
	// default, and one naming a ground this theme does not paint is dropped.
	foreach (bridge_button_grounds() as $key => $entry) {
		$button_fills[$key] = bridge_pick_token('buttons', 'fill', $raw_button_colors[$key] ?? '', $entry['fill']);
	}

	$buttons = array(
		'skin'   => bridge_pick_token('buttons', 'skin', $raw_buttons['skin'] ?? '', $db['skin']),
		'colors' => $button_fills,
	);

	// ---- Cards ------------------------------------------------------------
	$raw_cards = isset($raw['cards']) && is_array($raw['cards']) ? $raw['cards'] : array();
	$dc        = $defaults['cards'];

	$raw_card_colors = isset($raw_cards['colors']) && is_array($raw_cards['colors']) ? $raw_cards['colors'] : array();
	$card_colors     = array();

	// Keyed by ground rather than accumulated from what was submitted, so a
	// payload missing a ground gets the default for it and a payload naming a
	// ground the theme does not paint is dropped.
	foreach (bridge_card_grounds() as $key => $entry) {
		$card_colors[$key] = strtolower(
			bridge_hex_or($raw_card_colors[$key] ?? null, $entry['default'])
		);
	}

	/**
	 * The per-style settings.
	 *
	 * Walked from `bridge_card_styles()` rather than from what was submitted,
	 * the same way the grounds above are: a payload missing a style gets that
	 * style's defaults, a payload naming a style the theme does not draw is
	 * dropped, and a field a style does not have is dropped even if the style
	 * is real. So a saved record can only ever describe styles that exist,
	 * with fields those styles actually take.
	 */
	$raw_card_styles = isset($raw_cards['styles']) && is_array($raw_cards['styles']) ? $raw_cards['styles'] : array();
	$style_options   = bridge_card_style_options();
	$card_styles     = array();

	foreach (bridge_card_styles() as $slug => $entry) {
		$submitted = isset($raw_card_styles[$slug]) && is_array($raw_card_styles[$slug])
			? $raw_card_styles[$slug]
			: array();

		$style = array();

		foreach ((array) ($entry['fields'] ?? array()) as $field) {
			$allowed = $style_options[$field] ?? array();
			$default = (string) ($entry[$field] ?? '');

			// A field with no option list is a field the theme cannot check,
			// and an unchecked string is what the sanitiser exists to prevent.
			if (! $allowed) {
				continue;
			}

			$value = is_scalar($submitted[$field] ?? null) ? (string) $submitted[$field] : '';

			$style[$field] = in_array($value, $allowed, true) ? $value : $default;
		}

		$card_styles[$slug] = $style;
	}

	$cards = array(
		'padding' => bridge_pick_token('cards', 'padding', $raw_cards['padding'] ?? '', $dc['padding']),
		// Stored as a whole number of pixels. A radius is read off a design at
		// integer precision and nothing downstream wants 6.4px.
		'radius'  => (int) round(bridge_clamp_token('cards', 'radius', $raw_cards['radius'] ?? null, (float) $dc['radius'])),
		'shadow'  => bridge_pick_token('cards', 'shadow', $raw_cards['shadow'] ?? '', $dc['shadow']),
		// Words, so a whole number: wp_trim_words() counts them and half a
		// word is not a length.
		'excerpt' => (int) round(bridge_clamp_token('cards', 'excerpt', $raw_cards['excerpt'] ?? null, (float) $dc['excerpt'])),
		'colors'  => $card_colors,
		'styles'  => $card_styles,
	);

	// ---- Structure --------------------------------------------------------
	$raw_header = isset($raw['header']) && is_array($raw['header']) ? $raw['header'] : array();
	$raw_footer = isset($raw['footer']) && is_array($raw['footer']) ? $raw['footer'] : array();

	// The nested groups, read once. Without these the `?? ` fallbacks below
	// silently swallow an undefined variable and every logo and button setting
	// resolves to its default no matter what was saved.
	$raw_logo  = isset($raw_header['logo']) && is_array($raw_header['logo']) ? $raw_header['logo'] : array();
	$raw_cta   = isset($raw_header['cta']) && is_array($raw_header['cta']) ? $raw_header['cta'] : array();
	$raw_menus = isset($raw_header['menus']) && is_array($raw_header['menus']) ? $raw_header['menus'] : array();

	// `ctaBar` was this setting's name before the strip stopped holding the call
	// to action. Either key switches the bar on, so a site saved before the
	// rename keeps its bar. Deliberately an OR rather than "new key wins":
	// the seed ships `topBar` too, so an absent-key test would always find the
	// new key present and never reach the old one. Nothing is stuck on — the
	// options page submits a complete draft, so the first save writes the
	// record without the legacy key and this stops mattering.
	$top_bar = ! empty($raw_header['topBar']) || ! empty($raw_header['ctaBar']);

	// `inverseId` was the light logo's name while it was only ever shown under
	// a transparent header. Read when the new key is absent or empty rather
	// than only when it is absent: the seed ships `lightId`, so the merge hands
	// the sanitiser both keys and a plain `??` would always stop at the new
	// one. Nothing is lost by the looser test — 0 means "no light logo", which
	// is exactly when the old key is worth consulting.
	$light_id = max(0, (int) ($raw_logo['lightId'] ?? 0));

	if ($light_id <= 0) {
		$light_id = max(0, (int) ($raw_logo['inverseId'] ?? 0));
	}

	$cta_label = sanitize_text_field((string) ($raw_cta['label'] ?? ''));
	// esc_url_raw rather than a bare string: this becomes an href, and a
	// javascript: URL in a header would run on every page.
	$cta_url = esc_url_raw((string) ($raw_cta['url'] ?? ''));

	// The button used to be implied by having filled in both fields. Records
	// written under that rule carry no `enabled` key, so infer it from the
	// fields rather than switching an existing site's button off on upgrade.
	$cta_enabled = array_key_exists('enabled', $raw_cta)
		? ! empty($raw_cta['enabled'])
		: ('' !== $cta_label && '' !== $cta_url);

	$header = array(
		'layout'          => bridge_pick_token('header', 'layout', $raw_header['layout'] ?? '', $defaults['header']['layout']),
		'topBar'          => ! empty($top_bar),
		// Structural validation only. Whether the id still points at a live
		// menu is a question for render time — a menu deleted after it was
		// chosen must not silently rewrite the stored setting to 0, or the
		// choice is lost the moment someone opens the options page.
		'menus'           => array(
			'primary' => max(0, (int) ($raw_menus['primary'] ?? 0)),
			'utility' => max(0, (int) ($raw_menus['utility'] ?? 0)),
		),
		'background'      => bridge_pick_token('header', 'background', $raw_header['background'] ?? '', $defaults['header']['background']),
		'backgroundColor' => isset(bridge_palette_slugs()[(string) ($raw_header['backgroundColor'] ?? '')])
			? (string) $raw_header['backgroundColor']
			: $defaults['header']['backgroundColor'],
		'contrast'        => bridge_pick_token('header', 'contrast', $raw_header['contrast'] ?? '', $defaults['header']['contrast']),
		'sticky'          => ! empty($raw_header['sticky']),
		'border'          => ! empty($raw_header['border']),
		'paddingBlock'    => (int) round(bridge_clamp_token('header', 'paddingBlock', $raw_header['paddingBlock'] ?? null, (float) $defaults['header']['paddingBlock'])),
		'logo'            => array(
			'id'      => max(0, (int) ($raw_logo['id'] ?? 0)),
			'lightId' => $light_id,
			'height'  => (int) round(bridge_clamp_token('header', 'logoHeight', $raw_logo['height'] ?? null, (float) $defaults['header']['logo']['height'])),
		),
		'cta'             => array(
			'enabled' => $cta_enabled,
			'label'   => $cta_label,
			'url'     => $cta_url,
		),
	);

	$footer = array(
		'style' => bridge_pick_token('footer', 'style', $raw_footer['style'] ?? '', $defaults['footer']['style']),
	);

	// ---- Site output ------------------------------------------------------
	$raw_site = isset($raw['site']) && is_array($raw['site']) ? $raw['site'] : array();

	// Cast rather than defaulted: a boolean's "missing" and "off" are the same
	// answer, so there is nothing for a fallback to disambiguate.
	$site = array(
		'feeds' => ! empty($raw_site['feeds']),
	);

	// ---- Blocks -----------------------------------------------------------
	$raw_blocks = isset($raw['blocks']) && is_array($raw['blocks']) ? $raw['blocks'] : array();

	// Sorted and de-duplicated so two records describing the same set are
	// byte-identical — the options page compares them to decide whether there
	// is anything to save.
	$block_names = static function ($value): array {
		$names = array();

		foreach ((array) $value as $name) {
			if (! is_string($name)) {
				continue;
			}

			$name = strtolower(trim($name));

			// namespace/name is the only shape a block name takes, and this
			// value ends up in comparisons against the block registry.
			if (preg_match('#^[a-z][a-z0-9-]*/[a-z][a-z0-9-]*$#', $name)) {
				$names[] = $name;
			}
		}

		$names = array_values(array_unique($names));
		sort($names);

		return $names;
	};

	$disabled = $block_names($raw_blocks['disabled'] ?? array());
	$enabled  = $block_names($raw_blocks['enabled'] ?? array());

	// The editor cannot function without a few of these, so switching them off
	// is not a choice the record is allowed to hold.
	$disabled = array_values(array_diff($disabled, bridge_required_blocks()));

	// Off wins: a block in both lists is a contradiction, and the safer
	// reading of a contradiction in a locked-down theme is the narrower one.
	$enabled = array_values(array_diff($enabled, $disabled));

	return array(
		'brand'      => array('palette' => $palette),
		'typography' => $typography,
		'icons'      => $icons,
		'buttons'    => $buttons,
		'cards'      => $cards,
		'header'     => $header,
		'footer'     => $footer,
		'layout'     => $layout,
		'blocks'     => array(
			'enabled'  => $enabled,
			'disabled' => $disabled,
		),
		'site'       => $site,
	);
}

/**
 * Persist a token set, sanitising first.
 *
 * The full sanitised structure is stored rather than a sparse diff, so the
 * record is self-describing and portable to another site.
 *
 * @param array<string, mixed> $tokens Candidate tokens, possibly partial.
 * @return bool True when the stored value changed.
 */
function bridge_update_tokens(array $tokens): bool
{
	return update_option(BRIDGE_TOKENS_OPTION, bridge_sanitize_tokens($tokens), true);
}

/**
 * Merge a partial token fragment into what is already stored.
 *
 * @param array<string, mixed> $fragment Partial tokens.
 * @return bool True when the stored value changed.
 */
function bridge_patch_tokens(array $fragment): bool
{
	return bridge_update_tokens(bridge_merge_deep(bridge_get_tokens(), $fragment));
}

/**
 * Short fingerprint of the current token set.
 */
function bridge_tokens_fingerprint(): string
{
	return substr(md5((string) wp_json_encode(bridge_get_tokens())), 0, 12);
}

/**
 * The stored token fingerprint, for versioning token-derived assets.
 */
function bridge_tokens_version(): string
{
	$version = get_option(BRIDGE_TOKENS_VERSION_OPTION, '');

	return is_string($version) && '' !== $version ? $version : bridge_tokens_fingerprint();
}

/**
 * Drop every cached copy of the design system after a token change.
 *
 * Three caches matter, and missing any one produces the classic "I saved it
 * but nothing changed" report:
 *
 *   - Our own request-level memo.
 *   - WordPress's resolved theme.json (static properties on the resolver).
 *   - The generated global stylesheet in the object cache, which persists
 *     across requests wherever Redis or Memcached is configured.
 *
 * wp_clean_theme_json_cache() covers the last two.
 */
function bridge_flush_tokens(): void
{
	bridge_tokens_memo(null, true);

	if (function_exists('wp_clean_theme_json_cache')) {
		wp_clean_theme_json_cache();
	}

	$tokens = bridge_get_tokens();

	update_option(BRIDGE_TOKENS_VERSION_OPTION, bridge_tokens_fingerprint(), true);

	/**
	 * Fires after the design tokens change and every cache has been dropped.
	 *
	 * Later phases hang font preloading and icon sprite regeneration here;
	 * hosting-level cache purges belong here too.
	 *
	 * @param array<string, mixed> $tokens The newly resolved token set.
	 */
	do_action('bridge_tokens_changed', $tokens);
}

/**
 * Flush whenever the token option is written, however it was written.
 *
 * Hooking the generic option actions rather than the option-specific ones
 * catches direct update_option() calls from WP-CLI, migrations and future
 * REST handlers alike. All three pass the option name as the first argument.
 *
 * @param string $option Option name that changed.
 */
function bridge_maybe_flush_tokens($option): void
{
	if (BRIDGE_TOKENS_OPTION === $option) {
		bridge_flush_tokens();
	}
}
add_action('added_option', 'bridge_maybe_flush_tokens');
add_action('updated_option', 'bridge_maybe_flush_tokens');
add_action('deleted_option', 'bridge_maybe_flush_tokens');
